using UnityEngine;

public class DuckInfo : MonoBehaviour
{
    private string[] duckMessages = new string[]
    {
        "No Brasil, mais de 6 milhoes de pessoas, aproximadamente, tem algum tipo de deficiencia visual, segundo dados do Censo de 2010 realizado pelo IBGE. Destas, mais de 500 mil sao cegas, enquanto o restante possui baixa visao ou algum nivel de deficiencia visual parcial. \n\n     Essas informacoes sao importantes para a formulacao de politicas publicas de acessibilidade e inclusao, visando proporcionar maior acessibilidade, especialmente em areas como educacao, transporte  e servicos digitais.",
        "As principais causas de cegueira incluem doencas oculares, fatores geneticos, traumas, e complicacoes de outras condicoes medicas. As mais comuns sao:\n\n   Catarata:  e uma das principais causas de cegueira reversivel e pode ser tratada com cirurgia.\n\n    Glaucoma: Muitas vezes assintomatico em estagios iniciais, o que dificulta o diagnostico precoce.\n\n Degeneracao macular relacionada a idade (DMRI):  Comum em idosos e geralmente irreversivel.\n\n   Retinopatia diabetica: Resulta do diabetes mal controlado, causando danos aos vasos sanguineos da retina. \n\n    Outras doencas e fatores incluem: ceratocone, infeccoes, doencas conginitas, doencas hereditarias, traumas e lesoes oculares.  \n\n   A prevencao e o diagnostico precoce de algumas dessas condicoes sao fundamentais para evitar a cegueira ou reduzir seu impacto na qualidade de vida.",
        "Acessibilidade: \n\n    Leitores de Tela \n\n   Programas que leem o conteudo da tela em voz alta, permitindo que pessoas com deficiencia visual naveguem em computadores, smartphones e tablets.\n\n   Exemplos:\r\nJAWS (Job Access With Speech): Popular no Windows, usado principalmente no ambiente profissional e academico. Converte texto em audio e tem comandos para navegacao eficiente.\n\n VoiceOver: Disponivel em dispositivos da Apple (iPhone, iPad, Mac). Permite que usuarios naveguem pelas telas usando gestos, possibilitando facil acesso aos aplicativos.\n\n   NVDA (NonVisual Desktop Access): Um software gratuito para Windows, amplamente usado por sua acessibilidade e eficiencia.",
        "Acessibilidade: \n\n    Sistema Braile e a importancia da Leitura Tatil\n\n O sistema braille e uma forma de escrita tatil que utiliza pontos em relevo para representar letras, numeros e simbolos sendo uma ferramenta essencial para a alfabetizacao e o acesso a informacao por pessoas cegas ou com baixa visao.\n\n   Importancia do Braille:\n\n O braille nao e apenas uma forma de leitura; ele proporciona contato direto com a estrutura e ortografia da lingua, algo fundamental para o desenvolvimento da alfabetizacao.  Alem disso, o braille e indispensavel para que as pessoas possam ler textos em silencio, aprender a ortografia correta e desenvolver uma compreensao completa da estrutura das palavras.\nExemplos de Uso: Rotulos, embalagens, livros, publicacoes, material escolar e academico.",
        "Acessibilidade: \n\n    Dispositivos de Leitura com Camera OCR (Reconhecimento optico de Caracteres)\n\n    Descricao: Dispositivos portateis com cameras que capturam imagens de texto impresso e as convertem em audio. Eles ajudam no dia-a-dia em uma biblioteca ou supermercado, por exemplo, a pessoa pode usar o dispositivo para ler um livro ou verificar ingredientes e informacoes nutricionais em produtos.\n\n Exemplos:\n\n   OrCam MyEye: Dispositivo portatil que pode ser acoplado a oculos. Ele captura textos, identifica rostos e le codigos de barras, transformando em audio.\n\n KNFB Reader: Aplicativo para smartphones que tira fotos de textos impressos e os converte para audio instantaneamente.",
        "Acessibilidade: \n\n    Mapas Tateis e Piso tatil \n\n  Mapas e pisos com texturas especiais que permitem que pessoas cegas se orientem e se desloquem de forma segura em ambientes publicos, garantindo mais independencia e seguranca. \n\n   Exemplos: \n\n  Piso Tatil (podotatil): Pisos com texturas distintas (linhas e pontos) que servem como guia em areas de grande circulacao, como estacoes de transporte e calcadas. \n\n Mapas Tateis: Mapas em relevo ou braille para que pessoas cegas possam identificar a disposicao de espacos publicos, como shoppings, universidades e hospitais.",
        "Acessibilidade: \n\n    Tecnologia de Assistencia por Inteligencia Artificial \n\n  Aplicativos que utilizam IA para descrever o ambiente, identificar objetos e ate reconhecer rostos, auxiliando no cotidiano, tornando o dia a dia de pessoas com deficiencia visual mais interativo e seguro. \n\n  Exemplos: \n\n  Seeing AI: Aplicativo da Microsoft que identifica objetos, descreve cenas, reconhece textos e ate rostos conhecidos, proporcionando uma experiencia de leitura e interacao com o ambiente. \n\n Be My Eyes: Conecta pessoas cegas com voluntarios videntes via chamada de video, onde o voluntario pode descrever o ambiente ou identificar objetos e situacoes que o usuario necessita.",
        "Acessibilidade: \n\n    Audiodescricao em Videos e Espetaculos \n\n Narracao adicional que descreve elementos visuais importantes em filmes, programas, pecas de teatro e eventos ao vivo, proporcionando uma experiencia que pessoas cegas possam aproveitar conteudos audiovisuais com a mesma riqueza de detalhes.\n\n   Exemplos:\n\n   Streaming com audiodescricao: Plataformas como Netflix e Amazon Prime oferecem audiodescricao para varios filmes e series, descrevendo as cenas e acoes para que pessoas cegas possam compreender o conteudo visual.\n\n    Teatros e eventos ao vivo: Cada vez mais, teatros oferecem audiodescricao durante espetaculos, permitindo que pessoas com deficiencia visual participem plenamente da experiencia.",
    };

    public int duckIndex;

    public string GetInfoMessage()
    {
        if (duckIndex >= 0 && duckIndex < duckMessages.Length)
        {
            return duckMessages[duckIndex];
        }
        Debug.Log($"indice invalido ou fora do limite: {duckIndex}");
        return "Mensagem padrao de coleta de pato!";
    }
}